# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.define :mysql do |web_config|
        web_config.vm.network "private_network", ip: "192.168.10.10"
        web_config.vm.network :forwarded_port, guest: 3306, host: 13306
        web_config.vm.provision "puppet" do |puppet|
            puppet.manifest_file = "vm-mysql.pp"
        end
  end
end
